### ISSUE TITLE
Field names have changed in occurrences download?

### ISSUE THREAD

**Issue by raymondben** [AtlasOfLivingAustralia/biocache-service#158]
e.g. http://biocache.ala.org.au/ws/occurrences/index/download?q=text%3AAmblyornis%20newtonianus&reasonTypeId=10&sourceTypeId=2001&esc=%5C&sep=%09&file=data

Problems:
1. No data comes back at all right now; I assume that this is because of the indexing bug (no default SOLR search field set). I thought using `text:...` would get around that but it doesn't seem to have done so here
2. Perhaps more importantly, the field names appear to have changed - e.g. the previous "scientificName" is now "Scientific Name"? The previous "taxonNameOriginal" has been removed? or maps to some other field that I haven't spotted?
Is this field name change permanent? Unfortunately it has broken ALA4R.

**Comment by adam-collins** [comment]
Problem 1 
Should be fixed in the next index deploy. This is expected some time Monday.

Problem 2 
1. The use of download parameter dwcHeader=true provides more stable headers.
2. A more robust solution is to use the 'headings.csv' that is in the downloaded zip for a lookup between the output 'Column name' and the information in http://biocache.ala.org.au/ws/index/fields. At this point in time:
* column 'DwC Name' is the most suitable column for stable DwC field names. Unprocessed fields have the suffix '_raw' and while this is not likely to change it is not certain.
* column 'Field name' is for SOLR indexed or stored fields. Names suffixes '_dt', '_d', '_i', '_s' are expected to be removed. Names without these suffixes will not change. Fields may be added or removed.
biocache-service should have a metadata service for static csvs, e.g. headings.csv, species lists. The purpose would be to track when columns are added, removed, and provide mapping between a static value and the column name, incase columns are renamed.

**Comment by raymondben** [comment]
Thanks Adam, will look at those options.

**Comment by snubian** [comment]
It would be great to have a rough idea of when the "no data" issue above might be fixed. Still getting no data returned for a bunch of taxa (though most work fine). E.g. `Abrophyllum ornans` returns no occurrence records, either via the API or through a search on the web interface - though, oddly, a search for genus `Abrophyllum` includes the records for `A. ornans`.

**Comment by snubian** [comment]
There seems to be a workaround for this, at least for single species, which is to set the `taxon` parameter to the genus, then use the `taxon_name` field in the `fq` parameter to filter to the desired species. E.g.:

```
> x <- ALA4R::occurrences("Abrophyllum ornans", download_reason_id = 4)$data
> dim(x)
[1]  0 44
> x <- ALA4R::occurrences("Abrophyllum", download_reason_id = 4, fq = "taxon_name:Abrophyllum ornans")$data
> dim(x)
[1] 599  65
```

Actually `taxon` can be `kingdom:Plantae` or anything that includes the species.

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
